platform :ios, '7.0'

pod 'MJExtension'
pod 'MJRefresh'
pod 'LBBlurredImage'
pod 'TSMessages'
pod 'Mantle'
pod 'Masonry'
pod 'Reachability'
pod 'BlocksKit'
pod 'KVOController'
pod 'MBProgressHUD'
pod 'ODRefreshControl'
pod 'pop'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'IQKeyboardManager'
pod 'AFNetworking-RACRetryExtensions'
pod 'FDFullscreenPopGesture', '~> 1.1'
